### ISSUE TITLE
CryptSync deletes opened files

### ISSUE THREAD

**Issue by Reemmoo** [stefankueng/CryptSync#43]
Hi Stefan

I'm using CrypSync to sync my working-folders with OneDrive. My problem is, that a lot of times, when I open a file to read it or to work on it, ScryptSyc delete sometimes this touched files.
That happend when I make a new entry on my Keepass-file, or when I'm working wiht Excel-files or when I'm just reading a email (kbdx, xlsx or eml).

In the log I notice the following entries, for example when the Keepass-file was deletet:
_08/30/20 19:39:53 : ERROR:   Failed to encrypt file "D:\Systems\Passwords\Database_eway.kdbx" to "C:\Users\Remo\OneDrive\_eway_sync_OneDrive\D-DATA\Systems\Passwords\Database_eway.kdbx.7z"
08/30/20 19:40:02 : INFO:    file D:\Systems\Passwords\Database_eway.kdbx does not exist, delete file C:\Users\Remo\OneDrive\_eway_sync_OneDrive\D-DATA\Systems\Passwords\Database_eway.kdbx.7z_

You have any idea? Could it be, that CryptSync try to touch opened files an then runs into an error?

Thanks for your support.

Kind regards Remo

**Comment by stefankueng** [comment]
the entry
`08/30/20 19:39:53 : ERROR: Failed to encrypt file "D:\Systems\Passwords\Database_eway.kdbx" to "C:\Users\Remo\OneDrive_eway_sync_OneDrive\D-DATA\Systems\Passwords\Database_eway.kdbx.7z"`
results in the encrypted file being deleted (the one in the OneDrive folder), because in that case the encrypted file was already set to zero bytes. But that means in the next sync run, the original file is encrypted again. This does **not** delete the original file!

The entry
`08/30/20 19:40:02 : INFO: file D:\Systems\Passwords\Database_eway.kdbx does not exist, delete file C:\Users\Remo\OneDrive_eway_sync_OneDrive\D-DATA\Systems\Passwords\Database_eway.kdbx.7z`
however means that the original file is missing (really missing, just not accessible would not make this happen!)
So how is the original file missing?

**Comment by Reemmoo** [comment]
I realy don't know what happend. When I stop the CryptSync service there's no problem, I never lose opened or files I'll worked with when CryptSync isn't running. The original file is only missing after a run from CryptSync. That occurs not every time. I can't realy reproduce it. I had problems yesterday with some files. Today, until the moment, everything is working fine. I don't understand what is happend...

**Comment by stefankueng** [comment]
do you have by any chance `*.7z` in the list of files to be copied only, not encrypted?

**Comment by Reemmoo** [comment]
Hi Stefan,
i had to do a few tests first. Now i have found out why the problem occurred. I had easy2sync running as a background service. This service synchronizes my data with a NAS every few minutes. CryptSync apparently had problems with data that was synchronized by easy2sync. Since I stopped the easy2sync service, the problem not occurs more time.
What do you guess can be the problem? I would like to run easy2sync also in the background. For local synchronisation it works perfect for me. CryptSync I use to synchronise my data with OneDrive. Any idea?

**Comment by ghrasc** [comment]
Reemmoo, pls have a look at https://github.com/stefankueng/CryptSync/issues/70#issue-1004201925 - might be your issue as well.
