### ISSUE TITLE
When only copying files, new files result in a folder with .7z extension

### ISSUE THREAD

**Issue by account-sxf** [stefankueng/CryptSync#46]
## First off
I love this tool - Great job! Thank you so much for making it.

## Now, the issue I've discovered:
I have a folder pair set up for convenience that simply copies between locations (no encryption), and I use \*.\* to tell CryptSync this (via the "...but copied below:" field). However, when I create a file in the unecrypted side during sync it also creates a folder in the encrypted side with the name of the file being synced with.7z at the end. If I turn off the .7z option it does with the cryptsync extension.

This is compounded when you have encryption going in both direction and don't ignore .7z files, resulting in an infinite loop.

I have tried being more specific in the "...but copied below:" field, but the result is the same.

I really don't want to have to use a second app to do plain file copying. Thanks for taking a look at it.

**Comment by PBearSF** [comment]
Having the same issue since upgrading to version 1.34.  Have used CryptSync to back up my entire Documents folder to OneDrive for years, I have "Enter files you don't want encrypted but copied" set to "*.*" -- which used to work fine but, now, whenever an application makes an automatic backup of its own data file, CryptSync starts making unwanted encrypted files (AND a new encrypted folder) for that file instead of just copying it.

**Comment by stefankueng** [comment]
duplicate is #56
