### ISSUE TITLE
What is the mechanism of GPG encryption?

### ISSUE THREAD

**Issue by loveshizuka** [stefankueng/CryptSync#66]
I like CryptSync, easy to use and practical. 

I want to know what public key is used when using GPG for encryption? Can you explain the mechanism of GPG encryption? It would be better if I could customize the public key and private key.

**Comment by stefankueng** [comment]
CryptSync does not configure GPG at all. Which means you have to configure it yourself with your public/private keys before you can use it with CryptSync.
So you have to consult the GPG docs for such info.

That said, I don't recommend to use GPG with CryptSync, since the files get larger. Using the lzma compression with AES encryption is much better.
