### ISSUE TITLE
Feature Request: Have ability to choose order that events are logged 

### ISSUE THREAD

**Issue by vinnic62** [stefankueng/CryptSync#71]
Currently, the Cryptsync log displays events from earliest to latest. As I'm normally interested in the most recent activities, I need to scroll to the bottom to find what I'm looking for. Obviously, for my purposes, it would be useful to have logged events displayed in the reverse order (i.e. from latest to earliest). In that way, what I want will appear at the top of the log.

I realise that some people may prefer the current logging sequence. Therefore, I suggest a setting where users can choose the order that activities in the log file are displayed.

**Comment by stefankueng** [comment]
I'm sorry, but I doubt you will find any log files which do what you ask. Because it would require a lot more disk activity. You can't write to the beginning of a file just like that. You'd have to read the whole log file into memory, prepend the new log entries and write the whole file again.
appending to a log file however is possible without reading the whole file every time.
