### ISSUE TITLE
Files without extensions being deleted and recreated

### ISSUE THREAD

**Issue by mwalker212** [stefankueng/CryptSync#73]
Looking at the log, it appears that all files without an extension are not being found in the src folder during the deletion phase, then re-copied/encrypted in the encryption phase. This is on Windows 10. Examples from the log:

12/14/21 12:01:24 : INFO:    counterpart of file Homesite\metis\storage\app\avatars\-1.7z does not exist in src folder, delete file
12/14/21 12:01:24 : INFO:    counterpart of file Homesite\metis\storage\app\avatars\1.7z does not exist in src folder, delete file
12/14/21 12:01:24 : INFO:    counterpart of file Homesite\metis\storage\app\avatars\2.7z does not exist in src folder, delete file
12/14/21 12:01:24 : INFO:    counterpart of file Homesite\metis\storage\app\avatars\3.7z does not exist in src folder, delete file
12/14/21 12:01:24 : INFO:    counterpart of file Homesite\metis\storage\app\avatars\4.7z does not exist in src folder, delete file

12/14/21 12:31:03 : INFO:    settings: encrypt names: no, use 7z: yes, use GPG: no, use FAT workaround: yes, sync deleted: yes

12/14/21 12:31:09 : INFO:    encrypt file D:\Data\Homesite\metis\storage\app\avatars\-1 to E:\GoogleDrive\Data\Homesite\metis\storage\app\avatars\-1.7z
12/14/21 12:31:09 : INFO:    encrypt file D:\Data\Homesite\metis\storage\app\avatars\1 to E:\GoogleDrive\Data\Homesite\metis\storage\app\avatars\1.7z
12/14/21 12:31:09 : INFO:    encrypt file D:\Data\Homesite\metis\storage\app\avatars\2 to E:\GoogleDrive\Data\Homesite\metis\storage\app\avatars\2.7z
12/14/21 12:31:09 : INFO:    encrypt file D:\Data\Homesite\metis\storage\app\avatars\3 to E:\GoogleDrive\Data\Homesite\metis\storage\app\avatars\3.7z
12/14/21 12:31:09 : INFO:    encrypt file D:\Data\Homesite\metis\storage\app\avatars\4 to E:\GoogleDrive\Data\Homesite\metis\storage\app\avatars\4.7z

This occurs on every scan and these files and folders haven't changed for a very long time.

**Comment by dteys** [comment]
Same behavior on my PC since I upgraded to 1.4.2.439. Many files are "not found in src folder" and the 7z file is deleted (even though the source files are present and have not changed, and then the 7z files are recreated.
This behavior creates thousands of 7z files in my Recycle Bin every day and if left uncheck for a few days, it has so many files in Recycle Bin that Windows Explorer has trouble even loading the Recycle Bin window to display the list of files. Checking with command line shows that the multiple thousands of files in Recycle Bin are 7z files. 
Previous versions of CryptSync did not have this behavior with constant deletion and recreation of 7z files.
